# Uncomment the next line to define a global platform for your project
# platform :ios, '15.0'

target 'SlangTranslator' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SlangTranslator
pod 'Alamofire', '~> 5.4'
pod 'SwiftyJSON', '~> 4.0'
pod 'AWSMobileClient'
pod 'AWSPinpoint'
pod 'AWSS3'

plugin 'cocoapods-keys', {
  :project => "Eidolon",
  :keys => [
    "textURL",
	"imageURL",
	"accessKey",
	"secretKey"
  ]}


end
